DOMAIN = "smart_pool_assistant"

CONF_CHLOR_SENSOR = "chlor_sensor"
CONF_PH_SENSOR = "ph_sensor"
CONF_TEMP_SENSOR = "temp_sensor"
CONF_USAGE_BOOLEAN = "usage_boolean"

DEFAULT_CHLOR_TARGET = 1.5
DEFAULT_PH_TARGET = 7.2
DEFAULT_POOL_VOLUME = 0.96
DEFAULT_ACTIVE_PERCENT = 0.56

UPDATE_INTERVAL = 300
