log_maintenance:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: smart_pool_assistant
          domain: sensor
    type:
      required: true
      selector:
        select:
          options:
            - value: chlor
            - value: ph_plus
            - value: ph_minus
            - value: filter_clean
            - value: filter_replace
            - value: set_covered
            - value: set_usage
    amount:
      required: true
      selector:
        number:
          min: 0
          max: 5000
          step: 0.1
          mode: box
